### ISSUE TITLE
[request] skip config enabled usernames

### ISSUE THREAD

**Issue by Mickroz** [aequasi/valheim-discord-notifier#2]
Hi, i got the mod Server Messages (https://valheim.thunderstore.io/package/Zinal001/Server_Messages/) installed, but right now every message from that mod is also posted on discord, so for example the link to my discord server is posted on my discord server.
Anyway you can set a string/array of usernames in the config that will be skipped of posting on discord?

**Comment by cryptiklemur** [comment]
Good idea, yeah. I'll try to add that in the next update

**Comment by cryptiklemur** [comment]
Implemented in https://github.com/aequasi/valheim-discord-notifier/releases/tag/0.0.3

**Comment by Mickroz** [comment]
nice!
