### ISSUE TITLE
Request - Customize discord messages

### ISSUE THREAD

**Issue by Out2lunchUK** [aequasi/valheim-discord-notifier#3]
I just want to say thanks so much for this plugin. Im loving it, so easy and good to use.

Would it possible to edit then messages that get sent to Discord eg - 

Ie in the config, we could change the wording ourselves, this way we can easily change language, or make silly custom messages for humour?

[13:21] BOT Valheim-Server:: Bjôrn Wolfsen has joined the server!
[13:30] BOT Valheim-Server:: Bjôrn Wolfsen has left the server!

EG- 
Bjôrn Wolfsen arrives in a flash of light.
Bjôrn Wolfsen falls into an ooze and disappears.

**Comment by cryptiklemur** [comment]
Yeah, i do want to add this. Need to figure out the best way.

Main issue is that the config file doesn't allow arrays...

**Comment by cryptiklemur** [comment]
Implemented in https://github.com/aequasi/valheim-discord-notifier/releases/tag/0.0.3

**Comment by Out2lunchUK** [comment]
Wow your a legend. Thanks so much mate.
