### ISSUE TITLE
Compiling missing assembly

### ISSUE THREAD

**Issue by synxs-91** [aequasi/valheim-discord-notifier#4]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1503	Argument 1: cannot convert from 'ZRpc' to 'long'	DiscordNotifier	###\Patches\ZNetPatch.cs	41	Active
Error	CS1061	'ZNet' does not contain a definition for 'm_peers' and no accessible extension method 'm_peers' accepting a first argument of type 'ZNet' could be found (are you missing a using directive or an assembly reference?)	DiscordNotifier	###\Patches\ZNetPatch.cs	120	Active

pulling this as I attempt to build?
am I missing an reference?

**Comment by cryptiklemur** [comment]
Yeah, you need to get the publicized assemblies. I can't post them here, but if you doing the modding communities on discord can help you find those

**Comment by synxs-91** [comment]
brilliant thank you for this. posted another issue RE chat. really like this mod and would love to help work on it with you
